<div class="page-title-img">
    <img class="img-full" alt="page title img" src="<?= $this->basePath('skins/application/assets/images/headers/contact.png') ?>">
    <div class="page-title">
        <div class="container">
            <h1><b>Контакти</b></h1>
            <p>Швидко зв'язатися з нами для узгодження питань або бронювання столиків</p>
        </div><!-- .container -->
    </div>
</div><!-- .page-title-img -->

<section>
    <div class="container">
        <h3 class="text-center text-uppercase">Найдіть наш магазин біля нас</h3>
        <div class="map-container">
            <div id="map-canvas">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h3 class="text-uppercase">Надіслати листа</h3>
                <form id="form-contact" class="form-big" method="post" data-email-not-set-msg="Введіть email" data-message-not-set-msg="Введіть повідомлення" data-name-not-set-msg="Введіть ім'я" data-ajax-fail-msg="Наші сервери з обробки повідомнель знаходяться на технічних роботах. Спробуйте пізніше." data-success-msg="Ваше повідомлення було записане.">
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="text" name="name" placeholder="Ім'я">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="email" placeholder="Email">
                        </div>
                    </div>
                    <input type="text" name="subject" placeholder="Тема">
                    <textarea name="message" placeholder="Повідомлення"></textarea>
                    <div class="return-msg"></div>
                    <div class="text-right">
                        <input class="button-yellow button-text-low button-long button-low" type="submit" value="Надіслати">
                    </div>
                </form>
                <div class="margin-20"></div>
            </div>
            <div class="col-md-4">
                <h3 class="text-uppercase">Інформація</h3>
                <address class="address-big">
                    <p>
                        Піцерія, Головний офіс<br>
                        вул. Хрещатик 1, 03000<br>
                        Уиїв, Україна
                    </p>
                    <p>
                        Зарезервувати: 0 800 111 555 666<br>
                        Email: info@upmlpizza.com
                    </p>
                </address>
            </div>
        </div>
    </div><!-- .container -->
</section>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
