<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <?= $this->adminRenderFilterForm($this->filter, 3) ?>
            <div class="ibox-title">
                <h5><?= $this->translate('List of pages') ?></h5>

                <div class="btn-group pull-right">
                    <a href="<?= $this->urlWithParams('admin/page/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                        <?= $this->translate('Create') ?>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th id="id" class="sorting_asc sort text-center" data-sort="asc" data-name="id"><?= $this->translate('Id') ?></th>
                            <th id="status" class="sorting sort text-center" data-name="status" ><?= $this->translate('Status') ?></th>
                            <th class="sorting sort text-center" data-name="name" ><?= $this->translate('Name') ?></th>
                            <th class="sorting sort text-center" data-name="code"><?= $this->translate('Code') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) { ?>
                            <?php foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <td class="text-center">
                                        <?php if ($row->getStatus()) { ?>
                                            <span class="badge badge-primary">
                                                <?= $this->translate('Enabled') ?>
                                            </span>
                                        <?php } else { ?>
                                            <span class="badge badge-danger">
                                                <?= $this->translate('Disabled') ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                    <td class="text-center"><?= $row->getName() ?></td>
                                    <td class="text-center"><?= $row->getCode() ?></td>
                                    <td class="text-center">
                                        <a href="<?= $this->urlWithParams('admin/page/edit', ['id' => $row->getId()]) ?>">
                                            <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                        </a>
                                        /
                                        <a href="javascript:void(0);" data-url="<?= $this->urlWithParams('admin/page/delete', ['id' => $row->getId()]) ?>"
                                           data-id="<?= $row->getId() ?>" class="delete">
                                           <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="8" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this page!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>