<?php
$this->form->prepare();

$this->headScript()
    ->appendFile($this->basePath('skins/app-admin/js/plugins/codemirror/codemirror.js'))
    ->appendFile($this->basePath('skins/app-admin/js/plugins/codemirror/mode/textile/textile.js'));
?>

<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
                    <div class="panel-body">
                        <fieldset class="form-horizontal">
                            <?= $this->adminRenderForm($this->form) ?>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        CodeMirror.fromTextArea(document.getElementById('body'), {
            lineNumbers: true,
            matchBrackets: true,
            mode: "text/x-textile"
        });
    });
</script>