<div class="alert alert-warning">
    <h4><?= $this->translate('Ip pattern help') ?></h4>
    <p><?= $this->translate('Use "*" symbol for dynamic part of ip') ?></p>
    <p><?= $this->translate('Example: set "192.168.1.*" for 192.168.1.0 - 192.168.1.255 range of ip addresses') ?></p>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
                    <div class="panel-body">
                        <fieldset class="form-horizontal">
                            <?= $this->adminRenderForm($this->form) ?>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>