<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <?= $this->adminRenderFilterForm($this->filter, 2) ?>

            <div class="ibox-title">
                <h5><?= $this->translate('White ip addresses') ?></h5>
                <div class="btn-group pull-right">
                    <a href="<?= $this->urlWithParams('admin/white-ip/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                        <?= $this->translate('Create') ?>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th id="id" class="sorting_asc sort text-center" data-sort="asc" tabindex="0" data-name="id" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Id') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="ip" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Ip') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="comment" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Comment') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="createdAt" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Created at') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="creator" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Created by') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="changedAt" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Changed at') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="changer" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Changed by') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) { ?>
                            <?php foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <td class="text-center"><?= $row->getIp() ?></td>
                                    <td class="text-center"><?= $row->getComment() ?></td>
                                    <td class="text-center"><?= $row->getCreatedAt() ? $row->getCreatedAt()->format('Y-m-d H:m') : '-' ?></td>
                                    <td class="text-center"><?= $row->getCreator() ? $row->getCreator()->getName() : '-' ?></td>
                                    <td class="text-center"><?= $row->getChangedAt() ? $row->getChangedAt()->format('Y-m-d H:m') : '-' ?></td>
                                    <td class="text-center"><?= $row->getChanger() ? $row->getChanger()->getName() : '-' ?></td>
                                    <td class="text-center">
                                        <a href="<?= $this->urlWithParams('admin/white-ip/edit', ['id' => $row->getId()]) ?>">
                                            <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                        </a>
                                        /
                                        <a href="javascript:void(0);"
                                           data-url="<?= $this->urlWithParams('admin/white-ip/delete', ['id' => $row->getId()]) ?>"
                                           data-id="<?= $row->getId() ?>" class="delete">
                                           <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="8" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this ip!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>
