<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('List of ingredients') ?></h5>

                <div class="btn-group pull-right">
                    <a href="<?= $this->urlWithParams('admin/ingredient/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                        <?= $this->translate('Create') ?>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th class="sorting_asc sort" data-name="name" data-sort="asc"><?= $this->translate('Name') ?></th>
                            <th class="text-center"><?= $this->translate('Residues') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) {
                            /** @var \Application\Entity\Ingredient $row */
                            foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td><?= $row->getName() ?></td>
                                    <td>
                                        <?= $this->weightFormatter(isset($this->residues[$row->getId()]) ? $this->residues[$row->getId()] : 0) ?>
                                        <?= $this->translate('kg') ?>
                                    </td>
                                    <td class="text-center">
                                        <? if (!$row->isUsed()) { ?>
                                            <a href="<?= $this->urlWithParams('admin/ingredient/edit', ['id' => $row->getId()]) ?>">
                                                <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                            </a>
                                            /
                                            <a href="javascript:void(0);" data-url="<?= $this->urlWithParams('admin/ingredient/delete', ['id' => $row->getId()]) ?>"
                                               data-id="<?= $row->getId() ?>" class="delete">
                                                <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                            </a>
                                        <? } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="8" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this ingredient!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                cancelButtonText: "<?= $this->translate('Cancel') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>
