<h3 class="title-password-restore"><?= $this->translate('Password restore') ?></h3>

<?php $this->form->prepare() ?>
<?= $this->form()->openTag($this->form) ?>
<div class="form-group">
    <?php
    $email = $this->form->get('email');
    $emailMessages = $this->form->getMessages('email');
    $email->setAttributes([
        'id' => 'email',
        'required' => 'required',
        'class' => 'form-control' . (count($emailMessages) ? ' error' : ''),
    ]);
    ?>
    <?= $this->formElement($email) ?>

    <?php if (count($emailMessages)) { ?>
        <label class="error" for="email"><?= array_shift($emailMessages) ?></label>
    <?php } ?>
</div>
<div class="save">
    <?php
    $this->form->get('send')->setAttributes(
        ['class' => 'btn btn-primary block full-width ladda-button', 'data-style' => 'zoom-in']
    )
    ?>
    <?= $this->formElement($this->form->get('send')) ?>
</div>
<?= $this->form()->closeTag() ?>

<script>
    $(document).ready(function () {
        var l = $('.ladda-button').ladda();

        l.click(function () {
            l.ladda('start');
            l.parents('form').submit();
        });
    });
</script>
