<h3 class="title-password-restore"><?= $this->translate('Confirm password') ?></h3>

<?php $this->form->prepare() ?>
<?= $this->form()->openTag($this->form) ?>
<?php foreach (['password', 'password_repeat'] as $elementName) { ?>
    <div class="form-group">
        <?php
        $element = $this->form->get($elementName);
        $messages = $element->getMessages();
        $element->setAttributes([
            'id' => 'email',
            'required' => 'required',
            'class' => 'form-control' . (count($messages) ? ' error' : ''),
        ]);
        ?>
        <?= $this->formElement($element) ?>

        <?php if (count($messages)) { ?>
            <label class="error" for="<?= $element->getName() ?>"><?= array_shift($messages) ?></label>
        <?php } ?>
    </div>
<?php } ?>

<div class="save">
    <?php
    $this->form->get('save')->setAttributes(
        ['class' => 'btn btn-primary block full-width ladda-button', 'data-style' => 'zoom-in']
    )
    ?>
    <?= $this->formElement($this->form->get('save')) ?>
</div>
<?= $this->form()->closeTag() ?>

<script>
    $(document).ready(function () {
        var l = $('.ladda-button').ladda();

        l.click(function () {
            l.ladda('start');
            l.parents('form').submit();
        });
    });
</script>
