<section class="password-restore-form">
    <h1 class="title-password-restore"><?= $this->translate('Pass restore') ?></h1>

    <?php $this->form->prepare() ?>
    <?php $this->form->setAttribute('action', $this->url('forgot-password')); ?>
    <?= $this->form()->openTag($this->form) ?>

    <?php
    $classes = ['restore-password-form-email'];

    if ($this->form->getMessages('email')) {
        $classes[] = 'auth-form-warning_input';
    }

    $email = $this->form->get('email')->setAttributes([
        'id' => 'email',
        'class' => implode(' ', $classes)
    ]);
    ?>

    <p class="forgot-password-email"><?= $email->getLabel() ?></p>
    <?= $this->formElement($email) ?>
    <?php if ($this->form->getMessages('email')) { ?>
        <span class="auth-form-warning_text--show"><?= current($this->form->getMessages('email')) ?></span>
    <?php } ?>

    <p class="restore-password-message"><?= $this->translate('Pleace enter the e-mail you used to register on') ?> <br><?= $this->translate('Awsumsnacks') ?></p>

    <button name="forgot_passw" class="restore-password-form-button" formnovalidate><?= $this->translate('Restore my password') ?></button>
    <?= $this->form()->closeTag() ?>
</section>
