<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <?= $this->adminRenderTabForm($this->form, [
                'general' => ['title' => 'General', 'fields' => ['status', 'name', 'code', 'parent']],
                'description' => ['title' => 'Description', 'fields' => ['description_short', 'description_full']],
                'seo' => ['title' => 'Seo', 'fields' => ['html_title', 'meta_keywords', 'meta_description']],
            ]) ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        CKEDITOR.replace('description_full');
    });
</script>
