<?= $this->doctype() ?>
<html>
<head>
    <?php $this->headMeta()
        ->setCharset('utf-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ?>

    <?php $this->seoData() ?>
    <?= $this->headMeta() ?>
    <?= $this->headTitle() ?>

    <?= $this->headLink()
        ->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('skins/app-admin/favicon.ico')])
        ->appendStylesheet($this->basePath('skins/app-admin/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/font-awesome/css/font-awesome.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/animate.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/chosen/chosen.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/chosen/bootstrap-chosen.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/sweetalert/sweetalert.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/dataTables/datatables.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/toastr/toastr.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/ladda/ladda-themeless.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/summernote/summernote.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/iCheck/custom.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/jsTree/style.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/footable/footable.core.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/jasny/jasny-bootstrap.min.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/datapicker/datepicker3.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/custom/css/style.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/style.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/codemirror/codemirror.css'))
        ->appendStylesheet($this->basePath('skins/app-admin/css/plugins/codemirror/ambiance.css'))
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath('skins/app-admin/js/jquery-3.1.1.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/bootstrap.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/metisMenu/jquery.metisMenu.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/inspinia.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/pace/pace.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/chosen/chosen.jquery.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/sweetalert/sweetalert.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/toastr/toastr.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/ladda/spin.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/ladda/ladda.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/ladda/ladda.jquery.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/summernote/summernote.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/iCheck/icheck.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/jsTree/jstree.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/jasny/jasny-bootstrap.min.js'))
        ->appendFile($this->basePath('skins/app-admin/js/plugins/datapicker/bootstrap-datepicker.js'))
        ->appendFile($this->basePath('skins/app-admin/custom/js/main.js'))
        ->appendFile($this->basePath('skins/app-admin/custom/js/sorting.js'))
        ->appendFile($this->basePath('js/ckeditor/ckeditor.js'))
        ->appendFile($this->basePath('js/ckfinder/ckfinder.js'))
    ?>

    <script>
        (function (w, app) {
            app.goBack = function () {
                w.location.href = '<?= $this->comeBackUrl() ?>';
            };
        }(window, app));
    </script>
</head>
<body>
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element text-center">
                        <span>
                            <img alt="image" class="img-circle" width="100" height="100"
                                 src="<?= $this->basePath('skins/app-admin/custom/img/no-image.jpg') ?>"/>
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear">
                                <span class="block m-t-xs">
                                    <strong class="font-bold">
                                        <?= $this->identity()->getName() ?>
                                    </strong>
                                </span>
                                <span class="text-muted text-xs block">
                                    <?= $this->identity()->getRoles()->current()->getName() ?><b class="caret"></b>
                                </span>
                            </span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li>
                                <a href="<?= $this->urlWithParams('admin/user/edit', ['id' => $this->identity()->getId()]) ?>">
                                    <?= $this->translate('Profile') ?>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url('admin/signout') ?>"><?= $this->translate('Logout') ?></a>
                            </li>
                        </ul>
                    </div>
                </li>
                <?= $this->adminMenu() ?>
            </ul>
        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="<?= $this->url('admin/signout') ?>">
                            <i class="fa fa-sign-out"></i> <?= $this->translate('Logout') ?>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="wrapper wrapper-content">
            <div class="wrapper wrapper-content animated fadeInRight">
                <?= $this->content ?>
            </div>
        </div>
        <div class="footer text-center">
            <?= $this->adminCopyright() ?>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
<?= $this->adminFlashMessenger() ?>
</body>
</html>