<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <?= $this->adminRenderTabForm($this->form, [
                    'general'     => ['title' => 'General', 'fields' => ['category', 'receipt', 'status', 'name', 'code', 'price'], 'image_upload' => [
                        'script' => 'app-admin/helper/fieldset/base-file-upload',
                        'resource' => $this->form->getObject()->getImage(),
                    ]],
                    'description' => ['title' => 'Description', 'fields' => ['short_description', 'full_description']],
                    'seo'         => ['title' => 'Seo', 'fields' => ['html_title', 'meta_keywords', 'meta_description']],
                ])
            ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        CKEDITOR.replace('full_description');
    });
</script>
