<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('List of products') ?></h5>
                <div class="pull-right">
                    <a href="<?= $this->urlWithParams('admin/product/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                        <?= $this->translate('Create') ?>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting" >
                        <thead>
                            <tr>
                                <th id="id" class="sorting_asc sort text-center" data-name="id"><?= $this->translate('Id') ?></th>
                                <th id="status" class="sorting sort text-center" data-name="state"><?= $this->translate('Status') ?></th>
                                <th class="sorting sort" data-name="name"><?= $this->translate('Name') ?></th>
                                <th class="sorting sort" data-name="category"><?= $this->translate('Category') ?></th>
                                <th class="sorting sort text-center" data-name="category"><?= $this->translate('Price') ?></th>
                                <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->paginator as $product) { ?>
                                <tr>
                                    <td class="text-center"><?= $product->getId() ?></td>
                                    <td class="text-center">
                                        <?php if ($product->getStatus() == \Application\Entity\Product::STATUS_ENABLED) { ?>
                                            <span class="badge badge-primary">
                                                <?= $this->translate('Enabled') ?>
                                            </span>
                                        <?php } else { ?>
                                            <span class="badge badge-danger">
                                                <?= $this->translate('Disabled') ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                    <td><?= $product->getName() ?></td>
                                    <td>
                                        <?php if (!empty($product->getCategory())) { ?>
                                            <?= $product->getCategory()->getName() ?>
                                        <?php } ?>
                                    </td>
                                    <td class="text-center"><?= $product->getPrice() ?></td>
                                    <td class="text-center">
                                        <a href="<?= $this->urlWithParams('admin/product/edit', ['id' => $product->getId()]) ?>">
                                            <i class="fa fa-pencil" aria-hidden="true" title="Edit"></i>
                                        </a>
                                        /
                                        <a href="javascript:void(0);" data-url="<?= $this->urlWithParams('admin/product/delete', ['id' => $product->getId()]) ?>"
                                           data-id="<?= $product->getId() ?>" class="delete">
                                            <i class="fa fa-remove" title="Delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php if (!$this->paginator->count()) { ?>
                                <tr>
                                    <td colspan="9" class="text-center"><?= $this->translate('No records found') ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <?= $this->adminRowsPerPage() ?>
                    <?= $this->adminPagination($this->paginator) ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.delete').on('click', function () {
            var url = $(this).data('url');

            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this product!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>
