<div class="page-title-img">
    <img class="img-full" alt="page title img" src="<?= $this->basePath('skins/application/assets/images/headers/about.png') ?>">
    <div class="page-title">
        <div class="container">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet</p>
        </div><!-- .container -->
    </div>
</div><!-- .page-title-img -->

<section>
    <div class="container">
        <h1 class="bottom-line">About us</h1>
        <p class="text-center"><em>When gliding by the Bashee isles we emerged at last upon the great South Sea.</em></p>
        <div class="row">
            <div class="col-md-6">
                <h2>Our History</h2>
                <p>It may be that the primal source of all those pictorial delusions will be found among the oldest Hindoo, Egyptian, and Grecian sculptures. For ever since those inventive but unscrupulous times when on the marble panellings of temples, the pedestals of statues, and on shields, medallions, cups, and coins, the dolphin was drawn in scales of chain-armor like Saladin's, and a helmeted head like St. George's; ever since then has something of the same sort of license prevailed, not only in most popular pictures of the whale, but in many scientific presentations of him.</p>
            </div>
            <div class="col-md-6">
                <div class="margin-20"></div>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/rEk0AdJx9gw"></iframe>
                </div>
            </div>
        </div><!-- .row -->

        <div class="section-delimiter"></div>

        <div class="row">
            <div class="col-md-6">
                <div class="slider-single">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/4.jpg') ?>">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/4.jpg') ?>">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/4.jpg') ?>">
                </div>
                <div class="margin-20"></div>
            </div>
            <div class="col-md-6">
                <h2>Amazing Interior</h2>
                <p>It may be that the primal source of all those pictorial delusions will be found among the oldest Hindoo, Egyptian, and Grecian sculptures. For ever since those inventive but unscrupulous times when on the marble panellings of temples, the pedestals of statues, and on shields, medallions, cups, and coins, the dolphin was drawn in scales of chain-armor like Saladin's, and a helmeted head like St. George's; ever since then has something of the same sort of license prevailed, not only in most popular pictures of the whale, but in many scientific presentations of him.</p>
            </div>
        </div>
    </div>
</section>

<section class="bg-white bg-pattern">
    <div class="margin-50"></div>
    <div class="container">
        <div class="row centered-columns">
            <div class="col-md-6 centered-column responsive-column">
                <img class="img-responsive" alt="mobile" src="<?= $this->basePath('skins/application/assets/images/mobile.png') ?>">
            </div>
            <div class="col-md-6 centered-column responsive-column">
                <h1>Now availaible for your smartphones</h1>
                <p>
                    It was under very similar circumstances to the first performance; but this time he did not breast out the line; and hence, when the whale started to run, Pip was left behind on the sea, like a hurried traveller's trunk. Alas! Stubb was but too true to his word. It was a beautiful, bounteous, blue day.
                </p>
                <div class="margin-10"></div>
                <a href="#"><img class="btn-store" alt="app store" src="<?= $this->basePath('skins/application/assets/images/mobile_button1.png') ?>"></a>
                <a href="#"><img class="btn-store" alt="google play" src="<?= $this->basePath('skins/application/assets/images/mobile_button2.png') ?>"></a>
                <div class="margin-10"></div>
            </div>
        </div>
    </div><!-- .container -->
    <div class="margin-50"></div>
</section>

<section>
    <div class="container">
        <h1 class="text-center">Our Team</h1>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/1.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Tim Robinson</h4>
                                    <em>Master Chef</em>
                                </div>
                            </div><!-- .worker-head -->
                            <p class="worker-note">
                                When gliding by the Bashee isles we emerged at last upon the great South Sea.
                            </p>
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img-alt">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/2.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Hansom Rob</h4>
                                    <em>Pizza Master</em>
                                </div>
                            </div><!-- .worker-head -->
                            <p class="worker-note">
                                When gliding by the Bashee isles we emerged at last upon the great South Sea.
                            </p>
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                </div><!-- .row -->
            </div><!-- .col-md-6 -->
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/3.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>John Doe</h4>
                                    <em>Pasta chef</em>
                                </div>
                            </div><!-- .worker-head -->
                            <p class="worker-note">
                                When gliding by the Bashee isles we emerged at last upon the great South Sea.
                            </p>
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img-alt">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/4.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Mark Smiley</h4>
                                    <em>Assistant</em>
                                </div>
                            </div><!-- .worker-head -->
                            <p class="worker-note">
                                When gliding by the Bashee isles we emerged at last upon the great South Sea.
                            </p>
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                </div><!-- .row -->
            </div><!-- .col-md-6 -->
        </div><!-- .row -->
    </div><!-- .container -->
</section>

<script type="text/javascript" src="http://www.youtube.com/player_api"></script>
