<div class="page-title-img">
    <img class="img-full" alt="page title img" src="<?= $this->basePath('skins/application/assets/images/headers/about.png') ?>">
    <div class="page-title">
        <div class="container">
            <h1><b>Про нас</b></h1>
            <p>Наша історія, наші плани</p>
        </div><!-- .container -->
    </div>
</div><!-- .page-title-img -->

<section>
    <div class="container">
        <h1 class="bottom-line">Про нас</h1>
        <!--<p class="text-center"><em></em></p>-->
        <div class="row">
            <div class="col-md-6">
                <h2>Наша історія</h2>
                <p>Декілька століть назад люди, в пошуках смачної їжі, придумали піцу. Але сьогодні, в XXI ст. наші майстри перейняли всі традиції, методи приготування піци. Наш заклад рахується одним із найкращих по всій Україні. Зі всіх країн Європи, Азії та інших частин світу з'їзджаются люди аби скуштувати нашу легендарну піцу.</p>
            </div>
            <div class="col-md-6">
                <div class="margin-20"></div>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/GqwTmM0BksY"></iframe>
                </div>
            </div>
        </div><!-- .row -->

        <div class="section-delimiter"></div>

        <div class="row">
            <div class="col-md-6">
                <div class="slider-single">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/1.jpg') ?>">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/2.jpg') ?>">
                    <img alt="store" src="<?= $this->basePath('skins/application/assets/images/store/3.jpg') ?>">
                </div>
                <div class="margin-20"></div>
            </div>
            <div class="col-md-6">
                <h2>Дизайн</h2>
                <p><h3>Наш прекрасний дизайн відображається як на сайті так і в наших закладах.</h3></p>
            </div>
        </div>
    </div>
</section>

<section class="bg-white bg-pattern">
    <div class="margin-50"></div>
    <div class="container">
        <div class="row centered-columns">
            <div class="col-md-6 centered-column responsive-column">
                <img class="img-responsive" alt="mobile" src="<?= $this->basePath('skins/application/assets/images/mobile.png') ?>">
            </div>
            <div class="col-md-6 centered-column responsive-column">
                <h1>Нащі плани</h1>
                <p>
                    На даний момент в нас  2 глобальних плани. Ми хочемо розробити мбільні версіі наших додатків для швидшого і зручнішого замовлення наших товарів. Також ми хочемо вікрити більше закладів по всій Україні а в майбутньому ми хочемо стати міжнародною компанією.
                </p>
                <div class="margin-10"></div>
                <!--<a href="#"><img class="btn-store" alt="app store" src="<?// $this->basePath('skins/application/assets/images/mobile_button1.png') ?>"></a>
                <a href="#"><img class="btn-store" alt="google play" src="<?// $this->basePath('skins/application/assets/images/mobile_button2.png') ?>"></a>-->
                <div class="margin-10"></div>
            </div>
        </div>
    </div><!-- .container -->
    <div class="margin-50"></div>
</section>

<section>
    <div class="container">
        <h1 class="text-center">Команда</h1>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/1.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Єгор Третяков</h4>
                                    <em>Капітан команди</em>
                                </div>
                            </div><!-- .worker-head -->
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img-alt">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/2.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Андрій Третьяков</h4>
                                    <em>Учасник</em>
                                </div>
                            </div><!-- .worker-head -->
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                </div><!-- .row -->
            </div><!-- .col-md-6 -->
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/3.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>John Doe</h4>
                                    <em>Учасник</em>
                                </div>
                            </div><!-- .worker-head -->
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                    <div class="col-sm-6">
                        <div class="worker">
                            <div class="worker-head">
                                <div class="worker-img-alt">
                                    <div class="worker-img-layer-1">
                                        <div class="worker-img-layer-2">
                                            <div class="worker-img-content">
                                                <img alt="worker" src="<?= $this->basePath('skins/application/assets/images/workers/4.jpg') ?>">
                                                <div class="worker-socials">
                                                    <div class="worker-socials-content">
                                                        <a href="#"><i class="fa fa-google-plus"></i></a>
                                                        <a href="#"><i class="fa fa-twitter"></i></a>
                                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- .worker-img -->
                                <div class="worker-label">
                                    <h4>Mark Smiley</h4>
                                    <em>Учасник</em>
                                </div>
                            </div><!-- .worker-head -->
                        </div><!-- .worker -->
                    </div><!-- .col-sm-6 -->
                </div><!-- .row -->
            </div><!-- .col-md-6 -->
        </div><!-- .row -->
    </div><!-- .container -->
</section>

<script type="text/javascript" src="http://www.youtube.com/player_api"></script>
