<?php
/* @var $baseData array
 * @var $descrData array
 * @var $buttons array
 * @var $element \Zend\Form\Element
 */
$this->form->prepare();
$this->formRow()->setPartial('app-admin/user/form-row');
?>

<?= $this->form()->openTag($this->form) ?>

<ul class="nav nav-tabs" role="tablist" id="tab-list">
    <?php $i = 0; ?>
    <?php foreach ($this->tabs as $name => $tab) { ?>
        <li data-name="<?= $name ?>" role="presentation" class="tab-head <?= $i == 0 ? 'active' : ''?> <?= isset($tab['fields']) && is_array($tab['fields']) && array_intersect($this->invalidElementsNames, $tab['fields']) ? 'error' : ''?>">
            <a href="#<?= $name ?>" aria-controls="<?= $name ?>" role="tab" data-toggle="tab"><?= $tab['title'] ?></a>
        </li>
        <?php $i++; ?>
    <?php } ?>
</ul>

<div class="tab-content">
    <?php $i = 0; ?>
    <?php foreach ($this->tabs as $name => $tab) { ?>
        <div role="tabpanel" class="tab-pane <?= $i == 0 ? 'active' : '' ?>" id="<?= $name ?>">
            <div class="panel-body">
                <fieldset class="form-horizontal">
                    <?php if (isset($tab['script'])) { ?>
                        <?= $this->render($tab['script'], ['form' => $this->form]) ?>
                    <?php } else { ?>
                        <?php foreach ($tab['fields'] as $field) { ?>
                            <?php
                            $element = $this->form->get($field);
                            $rowClass = '';
                            $isCheckBox = $element instanceof \Zend\Form\Element\Checkbox;

                            if ($element instanceof \Zend\Form\Fieldset) {
                                echo $this->render($tab['options'][$field]['script'], [
                                    'fieldSet' => $element,
                                    'form' => $this->form,
                                    'options' => $tab['options'][$field],
                                ]);
                            } else {
                                $classes = ['form-control'];
                                $messages = $element->getMessages();

                                if (!empty($messages)) {
                                    $classes[] = 'error';
                                }

                                if ($element instanceof \Zend\Form\Element\Select) {
                                    $classes[] = 'chosen-select';
                                }

                                if ($element->getAttribute('class') == 'hidden' || $element instanceof \Zend\Form\Element\Hidden) {
                                    $rowClass = 'hidden';
                                }

                                $element->setAttributes(['class' => implode(' ', $classes)]);
                                $element->setOptions(['label_attributes' => ['class' => ($isCheckBox ? 'col-sm-8' : 'col-sm-2') . ' control-label']]);
                                $elementIsRequired = $form->getInputFilter()->get($element->getName())->isRequired();
                                $elementIsCsrf = get_class($element) == \Zend\Form\Element\Csrf::class;
                                $labelText = $element->getLabel() . ($elementIsRequired && !$elementIsCsrf ? ' *' : '');
                                ?>
                                <div class="form-group <?= $rowClass ?> <?= $isCheckBox ? 'ckbox': '' ?>">
                                    <?= $this->formLabel($element, $labelText) ?>
                                    <div class="<?= $isCheckBox ? 'col-sm-3' : 'col-sm-10' ?>">
                                        <?= $this->formElement($element) ?>
                                        <div class="errors">
                                            <?php foreach ($element->getMessages() as $message) { ?>
                                                <label id="" class="error" for="min>"><?= $message ?></label><br>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <?php foreach ($this->form->getFieldsets() as $fieldSet) {
                        $name = $fieldSet->getName();

                        if (!isset($tab[$name])) {
                            continue;
                        }

                        $options = $tab[$name];

                        if (isset($options['script'])) {
                            echo $this->render($options['script'], [
                                'fieldSet' => $fieldSet,
                                'form' => $this->form,
                                'resource' => (isset($options['resource'])) ? $options['resource'] : '',
                            ]);
                        }
                    } ?>
                </fieldset>
            </div>
        </div>
        <?php $i++; ?>
    <?php } ?>
</div>

<div class="row text-center form-tab-buttons">
    <?php foreach ($this->buttons as $element) {
        $classes = ['btn'];
        if ($element->getAttribute('name') == 'save') {
            $classes[] = 'btn-primary';
            $classes[] = 'ladda-button';
        }
        $element->setAttributes(['class' => implode(' ', $classes), 'data-style' => 'zoom-in']);
    ?>
        <?php if (count($this->buttons) > 1) { ?>
            <div class="col-xs-6 text-<?= ($element->getAttribute('name') == 'save') ? 'right' : 'left' ?>">
        <?php } ?>
        <?= $this->formElement($element) ?>
        <?php if (count($this->buttons) > 1) { ?>
            </div>
        <?php } ?>
    <?php } ?>
</div>

<?= $this->form()->closeTag($this->form) ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green'
        });

        $('.chosen-select').chosen({width: "100%"});
    });
</script>
