<a href="<?= $this->hrefFirst ?>" style="color: inherit; text-decoration: none;">
    <i class="glyphicon glyphicon-step-backward" style="transform: rotate(90deg)"></i>
</a>
<a href="<?= $this->hrefPrev ?>" style="color: inherit; text-decoration: none;">
    <i class="glyphicon glyphicon-triangle-left" style="transform: rotate(90deg)"></i>
</a>
<a href="<?= $this->hrefNext ?>" style="color: inherit; text-decoration: none;">
    <i class="glyphicon glyphicon-triangle-left" style="transform: rotate(270deg)"></i>
</a>
<a href="<?= $this->hrefLast ?>" style="color: inherit; text-decoration: none;">
    <i class="glyphicon glyphicon-step-backward"  style="transform: rotate(270deg)"></i>
</a>
