<?php
$this->form->prepare();
$tabs = [
    'general' => [
        'title' => $this->translate('General'),
        'fields' => ['description']
    ],
    'ingredients' => [
        'title' => $this->translate('Inventory'),
        'fields' => ['ingredients'],
        'options' => ['ingredients' => ['script' => 'app-admin/helper/table-ingredients-tab']]
    ],
];
?>

<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
                    <div class="panel-body">
                        <fieldset class="form-horizontal">
                            <?= $this->adminRenderTabForm($this->form, $tabs) ?>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
