<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('Ingredients income table') ?></h5>
                <div class="btn-group pull-right">
                    <div>
                        <a href="<?= $this->urlWithParams('admin/income/edit', ['id' => 0]) ?>"
                           class="btn-primary btn btn-xs">
                            <?= $this->translate('Create') ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('Id') ?></th>
                            <th class="text-center"><?= $this->translate('Ingredients') ?></th>
                            <th class="text-center"><?= $this->translate('Residues') ?></th>
                            <th id="description" class="text-center"><?= $this->translate('Description') ?></th>
                            <th class="text-center"><?= $this->translate('Created at') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) { ?>
                            <?php foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <td class="text-left">
                                        <? foreach ($row->getIngredients() as $documentIncomeIngredient) { ?>
                                            <b><?= $documentIncomeIngredient->getIngredient()->getName() ?>:</b>
                                            <?= $this->weightFormatter($documentIncomeIngredient->getWeight()) ?> <?= $this->translate('kg') ?>
                                            <br>
                                        <? } ?>
                                    </td>
                                    <td class="text-left">
                                        <? foreach ($row->getIngredients() as $documentIncomeIngredient) { ?>
                                            <b><?= $documentIncomeIngredient->getIngredient()->getName() ?>:</b>
                                            <?= $this->weightFormatter($documentIncomeIngredient->getResidue()) ?> <?= $this->translate('kg') ?>
                                            <br>
                                        <? } ?>
                                    </td>
                                    <td class="text-left"><?= $row->getDescription() ?></td>
                                    <td class="text-center">
                                        <?= $row->getCreatedAt() ? $row->getCreatedAt()->format('Y-m-d H:m') : '-' ?>
                                    </td>
                                    <td class="text-center">
                                        <? if (!$row->isUsed()) { ?>
                                            <a href="javascript:void(0);" data-url="<?= $this->urlWithParams('admin/income/delete', ['id' => $row->getId()]) ?>"
                                               data-id="<?= $row->getId() ?>" class="delete">
                                                <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                            </a>
                                        <? } ?>
                                    </th>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="6" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this income!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                cancelButtonText: "<?= $this->translate('Cancel') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>
