<?php
/**
 * @var \Application\Entity\DocumentIncome $row
 */
?>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('Ingredients income table') ?></h5>
                <div class="btn-group pull-right">
                    <div>
                        <a href="<?= $this->urlWithParams('admin/income/edit', ['id' => 0]) ?>"
                           class="btn-primary btn btn-xs">
                            <?= $this->translate('Create') ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('Id') ?></th>
                            <th class="text-center"><?= $this->translate('Ingredients') ?></th>
                            <th class="text-center"><?= $this->translate('Residues') ?></th>
                            <th id="description" class="text-center"><?= $this->translate('Description') ?></th>
                            <th class="text-center"><?= $this->translate('Created at') ?></th>
                            <th class="text-center"><?= $this->translate('Changed at') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) { ?>
                            <?php foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <td class="text-left"></td>
                                    <td class="text-left"></td>
                                    <td class="text-left"><?= $row->getDescription() ?></td>
                                    <td class="text-center">
                                        <?= $row->getCreatedAt() ? $row->getCreatedAt()->format('Y-m-d H:m') : '-' ?>
                                    </td>
                                    <td class="text-center">
                                        <?= $row->getChangedAt() ? $row->getChangedAt()->format('Y-m-d H:m') : '-' ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="6" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
