<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="alert alert-warning">
                <strong><?= $this->translate('Help') ?>:</strong>
                <?= $this->translate('the rules are applied top-down, {parent} - the string value to the application of the rules, {title} - the title of the current display element, {keywords} - his keywords, {description} - description. If the rule contains an empty field - the value remains unchanged. To clear the field using {empty}.')
                ?>
            </div>
            <?= $this->adminRenderFilterForm($this->filter, 2) ?>
            <div class="ibox-title">
                <h5><?= $this->translate('List of seo rules') ?></h5>

                <div class="btn-group pull-right">
                    <a href="<?= $this->urlWithParams('admin/seo/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                        <?= $this->translate('Create') ?>
                    </a>
                </div>
            </div>
            <?php $filterOn = $this->filter->filterIsEnabled(); ?>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th id="id" class="text-center"><?= $this->translate('Id') ?></th>
                            <?php if (!$filterOn) { ?>
                                <th class="column_sorting text-center"><?= $this->translate('Sorting') ?></th>
                            <?php } ?>
                            <th id="status" class="text-center"><?= $this->translate('Status') ?></th>
                            <th class="text-center"><?= $this->translate('Url pattern') ?></th>
                            <th class="text-center"><?= $this->translate('Title') ?></th>
                            <th class="text-center"><?= $this->translate('Keywords') ?></th>
                            <th class="text-center"><?= $this->translate('Description') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->rules->count()) { ?>
                            <?php foreach ($this->rules as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <?php if (!$filterOn) { ?>
                                        <td class="text-center"><?= $this->sortingData($row->getId(), $row->getSort(), 'admin/seo') ?></td>
                                    <?php } ?>
                                    <td class="text-center">
                                        <?php if ($row->getStatus()) { ?>
                                            <span class="badge badge-primary">
                                                <?= $this->translate('Enabled') ?>
                                            </span>
                                        <?php } else { ?>
                                            <span class="badge badge-danger">
                                                <?= $this->translate('Disabled') ?>
                                            </span>
                                        <?php } ?>
                                    </td>
                                    <td class="text-center"><?= $row->getUrl() ?></td>
                                    <td class="text-center"><?= $row->getTitle() ?></td>
                                    <td class="text-center"><?= $row->getKeywords() ?></td>
                                    <td class="text-center"><?= $row->getDescription() ?></td>
                                    <td class="text-center">
                                        <a href="<?= $this->urlWithParams('admin/seo/edit', ['id' => $row->getId()]) ?>">
                                            <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                        </a>
                                        /
                                        <a href="javascript:void(0);"
                                           data-url="<?= $this->urlWithParams('admin/seo/delete', ['id' => $row->getId()]) ?>"
                                           data-id="<?= $row->getId() ?>" class="delete">
                                           <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="8" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this seo rule!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>