<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><?= $this->translate('Forgot password') ?></title>
    </head>
    <body>
        <table class="body-wrap">
            <tr>
                <td></td>
                <td class="container" width="600">
                    <div class="content">
                        <table class="main" width="100%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td class="content-wrap">
                                    <table  cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td>
                                                Hello,<br />
                                                you are receiving the following notification from the <?= $this->url('home', [], ['force_canonical' => true]) ?> website.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                We received a request to restore or change your password. Please follow the link to perform update here:<br />
                                                <a href="<?= $this->url('admin/forgot-password-confirm', ['secret' => $this->secret], ['force_canonical' => true]) ?>">
                                                    <?= $this->url('admin/forgot-password-confirm', ['secret' => $this->secret], ['force_canonical' => true]) ?>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                If you haven't originated this request just ignore the message.<br />
                                                Please do not pass the message to the third person, thus we won't be able to grant your account secure.<br />
                                                Best wishes from AwsomeSnacks team!
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td></td>
            </tr>
        </table>
    </body>
</html>
