<?
    use Application\Entity\Order as OrderEntity;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('List of orders') ?></h5>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                            <tr>
                                <th id="id" class="sorting sort text-center" data-name="id"><?= $this->translate('Id') ?></th>
                                <th id="status" class="sorting sort text-center" data-name="status" ><?= $this->translate('Status') ?></th>
                                <th class="text-center"><?= $this->translate('Client data') ?></th>
                                <th class="sorting_desc sort text-center" data-name="created_at" data-sort="desc"><?= $this->translate('Created at') ?></th>
                                <th class="sorting sort text-center" data-name="changed_at"><?= $this->translate('Changed at') ?></th>
                                <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <? if ($this->paginator->count()) { ?>
                                <? foreach ($this->paginator as $row) { ?>
                                    <tr>
                                        <td class="text-center"><?= $row->getId() ?></td>
                                        <td class="text-center">
                                            <? if ($row->getStatus() == OrderEntity::STATUS_DELETED) { ?>
                                                <span class="badge badge-danger">
                                                    <?= $this->translate('Deleted') ?>
                                                </span>
                                            <? } else if ($row->getStatus() == OrderEntity::STATUS_CREATED) { ?>
                                                <span class="badge badge-warning">
                                                    <?= $this->translate('Created') ?>
                                                </span>
                                            <? } else if ($row->getStatus() == OrderEntity::STATUS_APPROVED) { ?>
                                                <span class="badge badge-info">
                                                    <?= $this->translate('Approved') ?>
                                                </span>
                                            <? } else if ($row->getStatus() == OrderEntity::STATUS_COOKED) { ?>
                                                <span class="badge badge-secondary">
                                                    <?= $this->translate('Cooked') ?>
                                                </span>
                                            <? } else if ($row->getStatus() == OrderEntity::STATUS_DELIVERED) { ?>
                                                <span class="badge badge-success">
                                                    <?= $this->translate('Delivered') ?>
                                                </span>
                                            <? } ?>
                                        </td>
                                        <td>
                                            <b><?= $this->translate('Phone') ?>:</b> <?= $row->getPhone() ?>
                                            <br>
                                            <b><?= $this->translate('Address') ?>:</b> <?= $row->getAddress() ?>
                                        </td>
                                        <td class="text-center"><?= $row->getCreatedAt() ? $row->getCreatedAt()->format('Y-m-d H:m') : '-' ?></td>
                                        <td class="text-center"><?= $row->getChangedAt() ? $row->getChangedAt()->format('Y-m-d H:m') : '-' ?></td>
                                        <td class="text-center">
                                            <? if ($row->getStatus() != OrderEntity::STATUS_DELETED) { ?>
                                                <a href="<?= $this->urlWithParams('admin/order/edit', ['id' => $row->getId()]) ?>">
                                                    <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                                </a>
                                            <? } else { ?>
                                                <a href="<?= $this->urlWithParams('admin/order/view', ['id' => $row->getId()]) ?>">
                                                    <i class="fa fa-eye" title="<?= $this->translate('View') ?>"></i>
                                                </a>
                                            <? } ?>
                                            <? if (($this->identity()->isAdmin() || $this->identity()->isOperator())
                                                    && $row->getStatus() != OrderEntity::STATUS_DELETED) { ?>
                                                /
                                                <a href="javascript:void(0);"
                                                   data-url="<?= $this->urlWithParams('admin/order/delete', ['id' => $row->getId()]) ?>"
                                                   data-id="<?= $row->getId() ?>" class="delete">
                                                   <i class="fa fa-remove red" title="<?= $this->translate('Delete') ?>"></i>
                                                </a>
                                            <? } ?>
                                        </td>
                                    </tr>
                                <? } ?>
                            <? } else { ?>
                                <tr>
                                    <td colspan="6" class="text-center"><?= $this->translate('No records found') ?></td>
                                </tr>
                            <? } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('are you sure you want to delete this order!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>
