<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?= $this->translate('List of orders') ?></h5>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('Status') ?></th>
                            <th class="text-center"><?= $this->translate('Address') ?></th>
                            <th class="text-center"><?= $this->translate('Phone') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <? if ($this->paginator->count()) { ?>
                            <? foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td><?= $row->getStatus() ?></td>
                                    <td><?= $row->getAddress() ?></td>
                                    <td><?= $row->getPhone() ?></td>
                                </tr>
                            <? } ?>
                        <? } else { ?>
                            <tr>
                                <td colspan="3" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <? } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
