<section id="cart">
    <div class="container">
        <div class="cart-content">
            <div class="cart-close cart-trigger"><i class="fa fa-close"></i></div>
            <div class="border-lines-container">
                <h1 class="no-top-margin border-lines">Cart</h1>
            </div>
            <form action="<?= $this->url('order') ?>" method="post">
                <? if (!$this->products->count()) { ?>
                    <center>There are no items in the cart yet</center>
                    <hr>
                <? } else { ?>
                    <? foreach ($this->products as $product) { ?>
                        <?= $this->cartProduct($product) ?>
                    <? } ?>
                    <div class="product-preview-small">
                        <div class="product-img">
                            <i class="fa fa-truck"></i>
                        </div>
                        <div class="product-content">
                            <div class="row">
                                <div class="col-md-8">
                                    <h4 class="product-title">Delivery</h4>
                                </div>
                                <div class="col-md-4 product-price">
                                    free
                                </div>
                            </div>
                        </div><!-- .product-content -->
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="text" name="address" placeholder="Address" style="margin: 5px 0;">
                        </div>
                        <div class="col-sm-6">
                            <div class="text-right text-bigger" style="margin-top: 10px;">Total: $<?= $this->total ?></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="tel" name="phone" id="phone" style="margin: 5px 0;">
                        </div>
                        <div class="col-sm-6 text-right">
                            <a class="button-yellow button-long with-right-arrow form-submit-trigger">MAKE YOUR ORDER</a>
                        </div>
                    </div>
                <? } ?>
            </form>
        </div><!-- .cart-content -->
    </div><!-- .container -->
</section><!-- #cart -->

<style>
    div.intl-tel-input {
        width: 100%;
    }
    #phone {
        margin: 5px 0;
        width: 100%;
        margin: 15px 0;
        font-style: italic;
        font-size: 15px;
        color: #343434;
        padding: 8px 17px 8px 52px;
        border: none;
        outline: none;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        border: 1px #ddd solid;
    }
</style>
