<?php $this->form->prepare(); ?>

<div class="row">
    <div class="col-lg-12">
        <div class="tabs-container">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
                    <div class="panel-body">
                        <fieldset class="form-horizontal">
                            <?= $this->adminRenderForm($this->form) ?>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>