<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <?= $this->adminRenderFilterForm($this->filter) ?>

            <div class="ibox-title">
                <h5><?= $this->translate('List of users') ?></h5>
                <div class="btn-group pull-right">
                    <div>
                        <a href="<?= $this->urlWithParams('admin/user/edit', ['id' => 0]) ?>" class="btn-primary btn btn-xs">
                            <?= $this->translate('Create') ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable use-sorting">
                        <thead>
                        <tr>
                            <th id="id" class="sorting_desc sort text-center" data-sort="desc" tabindex="0" data-name="id" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Id') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="last_name" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Name') ?></th>
                            <th class="sorting sort text-center" data-sort="" tabindex="0" data-name="email" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"><?= $this->translate('Email') ?></th>
                            <th id="actions" class="text-center"><?= $this->translate('Actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->paginator->count()) { ?>
                            <?php foreach ($this->paginator as $row) { ?>
                                <tr>
                                    <td class="text-center"><?= $row->getId() ?></td>
                                    <td class="text-center"><?= $row->getName() ?></td>
                                    <td class="text-center"><?= $row->getEmail() ?></td>
                                    <td class="text-center">
                                            <a href="<?= $this->urlWithParams('admin/user/edit', ['id' => $row->getId()]) ?>">
                                                <i class="fa fa-pencil" title="<?= $this->translate('Edit') ?>"></i>
                                            </a>
                                            /
                                            <a href="<?= $this->urlWithParams('admin/user/edit-password',
                                                ['id' => $row->getId()]) ?>">
                                                <i class="fa fa-pencil"
                                                   title="<?= $this->translate('Change password') ?>"></i>
                                            </a>
                                            /
                                            <a href="javascript:void(0);"
                                               data-url="<?= $this->urlWithParams('admin/user/delete', ['id' => $row->getId()]) ?>"
                                               data-id="<?= $row->getId() ?>" class="delete">
                                               <i class="fa fa-remove" title="<?= $this->translate('Delete') ?>"></i>
                                            </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="5" class="text-center"><?= $this->translate('No records found') ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div>
                        <?= $this->adminRowsPerPage() ?>
                        <?= $this->adminPagination($this->paginator) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal inmodal" id="users-mail-modal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                    <script type="text/javascript">
                        $(function () {
                            $("#categories-list").on("click", function () {
                                $('#users-mail-modal').find('.modal-title').text(
                                    $("#categories-list option:selected").text()
                                );
                            });
                        });
                    </script>
                </h4>
            </div>
            <div class="modal-body">
                <fieldset class="form-horizontal form-wrapper"></fieldset>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white close-modal"
                        data-dismiss="modal"><?= $this->translate('Close') ?></button>
                <button type="button"
                        class="btn btn-primary send" data-style="zoom-in"><?= $this->translate('Send') ?></button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').on('click', function () {
            var url = $(this).data('url');
            swal({
                title: "<?= $this->translate('Are you sure?') ?>",
                text: "<?= $this->translate('You will not be able to recover this user!') ?>",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<?= $this->translate('Yes, delete it!') ?>",
                closeOnConfirm: false
            }, function () {
                location.href = url;
            });
        });
    });
</script>